language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

before_script:
  - npm install firebase-tools
  - npm install

jobs:
  include:
    - stage: test
      - npm test
    - stage: build
      if: (branch = master) AND (type NOT IN (pull_request))
      script:
        - npm run build
        - firebase deploy --non-interactive --token $FIREBASE_TOKEN

after_failure: cat /home/travis/.npm/_logs/*.log