language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

before_script:
  - npm install firebase-tools
  - npm install

jobs:
  include:
    - stage: test
      name: "Testing"
      script:
        - npm test
    - stage: deploy
      name: "Deploying to Firebase"
      if: (branch = master) AND (type NOT IN (pull_request))
      script:
        - npm run build
        - firebase deploy --non-interactive --token $FIREBASE_TOKEN