language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - npm install firebase-tools
  - npm install

script:
  - npm test 
  - npm run build

after_failure: cat /home/travis/.npm/_logs/*.log