language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - npm install firebase-tools
  - npm install

script:
  - npm test

jobs:
  include:
    - stage: deploy
      if: (branch = master) AND (type NOT IN (pull_request))
        script:
          - npm run build
          - firebase deploy --non-interactive --token $FIREBASE_TOKEN