language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - npm install firebase-tools
  - npm install

script:
  - npm test

after_success:
  script:
    - npm run build
    - firebase deploy --non-interactive --token $FIREBASE_TOKEN
  branches:
    only:
      - master