language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - npm install firebase-tools
  - npm install

set -e

script:
  - npm test 
  - npm run build

after_failure: cat /home/travis/.npm/_logs/2018-11-17T00_35_48_731Z-debug*.log