language: node_js
node_js:
  - '10'

cache:
  directories:
  - node_modules

before_script:
  - npm install firebase-tools
  - npm install
  - cd server
  - npm install
  - cd ..

jobs:
  include:
  - stage: test
    name: Testing
    script:
      - npm test
  - stage: deploy
    name: Deploying to Firebase and GAE
    if: "(branch = master) AND (type NOT IN (pull_request))"
    script:
      - npm run build
      - firebase deploy --non-interactive --token $FIREBASE_TOKEN
      - cd server
      - gcloud app deploy